import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { App } from '@/app/App';
import '@fontsource/poppins/latin-400.css';
import '@fontsource/poppins/latin-500.css';
import '@fontsource/poppins/latin-600.css';
import '@fontsource/poppins/latin-700.css';
import '@fontsource/inknut-antiqua/latin-600.css';
import '@/styles/index.css';
import '@/styles/landing.css';
import '@/styles/territory.css';
import '@/styles/content-pages.css';
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
